name: Advanced Contains Example

on: push

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set output
        id: vars
        run: echo "::set-output name=example::hello world"

      - name: Use Output in Condition
        if: contains(steps.vars.outputs.example, 'world')
        run: echo "The output contains 'world'."
