name: Expressions Advanced

on: push

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Step for Feature Branches
        if: startsWith('Hello world', 'He')
        run: echo "Returns true when param-a starts with param-b"

      - name: Use Output in Condition
        if: contains('Hello world', 'world')
        run: echo "The output contains 'world'."

      - name: Create Custom Message
        run: echo "${{ format('Hello, {0}!', 'World') }}"
