name: Triggers
on:
  push:
    branches:
      - main
      - aprendiendo-github-actions
      - releases/**
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**.js"
  issues:
    types:
      - labeled
  issue_comment:
    types: [created, deleted]
  workflow_dispatch:
    inputs:
      lenguaje_favorito:
        description: "Lenguaje favorito"
        default: Javascript
        required: true
        type: choice
        options:
          - Python
          - JavaScript
          - Go
      nombre:
        description: "Tu nombre es"
        required: true
        default: Neider
        type: string
  schedule:
    - cron: "15 22 * * *"
jobs:
  hola-mundo-manual:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Definir nombre
        run: echo "USERNAME=${{ inputs.nombre }}" >> $GITHUB_ENV
      - name: Definir lenguaje
        run: echo "LANGUAGE=${{ inputs.lenguaje_favorito }}" >> $GITHUB_ENV
      - name: Correr script
        run: node index.js
  hola-mundo:
    if: ${{ github.event_name != 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Definir variable
        run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV
      - name: Correr script
        run: node index.js
