name: Triggers
on:
  push:
    branches:
      - main
      - aprendiendo-github-actions
      - releases/**
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**.js"
  issues:
    types:
      - labeled
  issue_comment:
    types: [created, deleted]
  workflow_dispatch:
    inputs:
      nombre:
        description: "Tu nombre es"
        required: true
        default: "Neider"
        type: string
  schedule:
    - cron: "15 22 * * *"
jobs:
  hola-mundo-manual-tigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Definir nombre
        run: echo "USERNAME=${{ github.event.inputs.nombre }}" >> $GITHUB_ENV
      - name: Correr script
        run: node index.js
